config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: %i[index show] do
    member do
      post :cancel
    end
  end

  resources :slots, only: %i[index]
  root "orders#index"
end

app/models/application_record.rb
# frozen_string_literal: true

# Base application model
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  has_many :orders, dependent: :restrict_with_error

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :address, presence: true
end

app/models/order.rb
# frozen_string_literal: true

# Customer order
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates :customer, presence: true
  validates :delivery_time, presence: true
  validates :product, presence: true
  validates :status, presence: true

  enum status: { todo: 0, delivered: 1, cancelled: 2}

  scope :to_prepare, ->(datetime) { where(delivery_time: datetime + 1.hour) }
  scope :by_product, ->(product_id) { where(product_id: product_id) }

  FIRST_DELIVERY_HOUR = 8
  LAST_DELIVERY_HOUR = 19

  def todo?
    status == 'todo'
  end

end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :orders, dependent: :restrict_with_error

  validates :name, presence: true
  validates :price, numericality: true, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

# Controller for listing and showing all Orders
class OrdersController < ApplicationController
  before_action :set_order, except: [:index]
  before_action :set_date, only: [:index]

  def index
    @orders = Order.where(Order.arel_table[:delivery_time].gteq(@date.beginning_of_day))
                   .where(Order.arel_table[:delivery_time].lteq(@date.end_of_day))
                   .includes(:customer, :product)
                   .order(:delivery_time)
  end

  def show
    set_order
  end

  def cancel
    if @order
      @order.update_columns(status: 'cancelled', comment: params[:comment])
      flash[:notice] = "Order ##{@order.id} Cancelled Successfully"
    else
      flash[:notice] = "Order not found with id ##{params[:id]}"
    end

    redirect_to orders_path
  end

  private

  def set_date
    @date = if params[:date]
              Date.parse(params[:date])
            else
              Date.current
            end
  end

  def set_order
    @order = Order.find_by(id: params[:id])
  end
end

app/controllers/slots_controller.rb
# frozen_string_literal: true

# Controller for viewing slots
class SlotsController < ApplicationController
  def index
    set_date
    set_orders
  end

  private

  def set_date
    @date = if params[:date]
              Date.parse(params[:date]).beginning_of_week
            else
              Date.current.beginning_of_week
            end
  end

  def set_orders
    @data = {}

    [*@date.beginning_of_week..@date.end_of_week].each do |date|
      [*Order::FIRST_DELIVERY_HOUR..Order::LAST_DELIVERY_HOUR].each do |hour|
        @data[date] = {} if @data[date].nil?
        @data[date][hour] = {} if @data[date][hour].nil?

        orders = Order
          .joins(:product)
          .includes(:product)
          .where('orders.delivery_time': date.to_datetime.change(hour: hour))

        orders.each do |order|
          if @data[date][hour][order.product.name].nil?
            @data[date][hour][order.product.name] = 1
          else
            @data[date][hour][order.product.name] =  @data[date][hour][order.product.name] + 1
          end
        end
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application helper
module ApplicationHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

# Orders helper
module OrdersHelper
end

app/helpers/slots_helper.rb
# frozen_string_literal: true

# Slots helper
module SlotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <title>Bergamotte</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav>
      <strong>
        <%= link_to "Orders", orders_path %>
        |
        <%= link_to "Slots", slots_path %>
      </strong>
    </nav>
    <hr/>
    <%= yield %>
  </body>
</html>

app/views/orders/_cancel_form.html.erb
  <a id="cancelOrder#<%=order.id%>" class='cancel-order'>cancel</a>

  <div id="cancelModal<%=order.id%>" class="modal">
    <div class="modal-content">
      <span class="close">&times;</span>
      <p>Reason to Cancel Order#<%=order.id%></p>
      
      <%= form_tag(cancel_order_path(order), :method => "post") do %>
        <%= label_tag(:comment, "Comment:") %>
        <%= text_area_tag(:comment)%>


        <%= submit_tag("Cancel") %>
      <% end %>
    </div>
  </div>

app/views/orders/index.html.erb
<p id="notice">
  <%= notice %>
</p>
<h1>
  <%= "Orders for #{@date}" %>
</h1>
<div>
  <%= link_to "Previous Date", orders_path(date: @date - 1.day) %>
  |
  <%= link_to "Next Date", orders_path(date: @date + 1.day) %>
</div>
<hr/>
<% if @orders.any? %>
  <table>
    <thead>
      <tr>
        <th>Delivery time</th>
        <th>Status</th>
        <th>Customer</th>
        <th>Product</th>
        <th>Price</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td>
            <%= order.delivery_time %>
          </td>
          <td>
            <%= order.status %>
          </td>
          <td>
            <%= order.customer.name %>
          </td>
          <td>
            <%= order.product.name %>
          </td>
          <td>
            <%= number_to_currency order.product.price %>
          </td>
          <td>
            <%= link_to 'Show', order %>
          </td>
          <% if order.todo? %>
            <td>
               <%= render 'cancel_form',  :order => order %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h4>No orders for this day</h4>
<% end %>

<script type="text/javascript">
$(document).ready(function(){
  $(".cancel-order").click(function(){
    id = "cancelModal"+this.id.split('#')[1]
    $("#"+id).css("display", "block");

  });

  $('.close').click(function(){
     $('.modal').css("display", "none");

  })
});
</script>

app/views/orders/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<p>
  <strong>Delivery time:</strong>
  <%= @order.delivery_time %>
</p>
<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>
<p>
  <strong>Product:</strong>
  <%= @order.product.name %>
</p>
<p>
  <strong>Customer:</strong>
  <%= @order.customer.name %>
</p>
<p>
  <strong>Address:</strong>
  <%= @order.customer.address %>
</p>

<%= link_to 'Back', orders_path(date: @order.delivery_time.to_date) %>

app/views/slots/index.html.erb
<h1>
  <%= "Slots overview for week starting #{@date}" %>
</h1>
<div>
  <%= link_to "Previous Week", slots_path(date: @date - 1.week) %>
  |
  <%= link_to "Next Week", slots_path(date: @date + 1.week) %>
</div>
<hr/>
<table>
  <thead>
    <tr>
      <th>
        Hour
      </th>
      <% @data.each do |date, values| %>
        <th>
          <%= date %>
        </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% [*Order::FIRST_DELIVERY_HOUR..Order::LAST_DELIVERY_HOUR].each do |hour| %>
      <tr>
        <th>
          <%= hour %>
        </th>
          <% @data.each do |date, values| %>
            <td>
              <% @data[date][hour].each do |key, value| %>
                <%= key %> <%= value %>
                </br>
              <% end %>
             </td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>